# Generated by Django 2.2 on 2022-04-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('feedback_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Consumer_Feedback_Details',
            },
        ),
        migrations.CreateModel(
            name='ConsumerModel',
            fields=[
                ('consumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=1000)),
                ('profile', models.ImageField(default=False, upload_to='')),
                ('address', models.TextField(default=False, max_length=100)),
                ('password', models.CharField(max_length=2000)),
                ('status', models.CharField(default='pending', max_length=500)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Consumer_Details',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('cart_id', models.IntegerField()),
                ('order_status', models.CharField(default='pending', max_length=50)),
                ('payment_mode', models.CharField(default='pending', max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumerapp.ConsumerModel')),
            ],
            options={
                'db_table': 'user_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumerapp.CartModel')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.ProductModel')),
            ],
            options={
                'db_table': 'user_cart_items',
            },
        ),
    ]
