# Generated by Django 2.2 on 2022-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.CharField(max_length=10)),
                ('prod_category', models.CharField(default=False, max_length=10)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField()),
                ('prod_units', models.CharField(default=False, max_length=20)),
                ('prod_description', models.TextField(max_length=500)),
                ('prod_image', models.ImageField(upload_to='images/')),
                ('prod_status', models.CharField(default='available', max_length=50)),
                ('prod_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
