# Generated by Django 2.2 on 2022-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=50)),
                ('profile', models.ImageField(default=False, upload_to='')),
                ('address', models.TextField(default=False, max_length=100)),
                ('password', models.CharField(max_length=55)),
                ('status', models.CharField(default='pending', max_length=500)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Supplier_Details',
            },
        ),
        migrations.CreateModel(
            name='SupplierVerifyModel',
            fields=[
                ('supplierverify_id', models.AutoField(primary_key=True, serialize=False)),
                ('distributor_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.BigIntegerField(null=True)),
                ('address', models.TextField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('isimark', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='', upload_to='')),
                ('status', models.CharField(default='pending', max_length=500)),
                ('verify_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Supplier_Verified_Details',
            },
        ),
    ]
